"""add email auth columns

Revision ID: 2c753cc36a34
Revises: f90ee39b8087
Create Date: 2026-09-12 11:39:57.438709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c753cc36a34'
down_revision: Union[str, None] = 'f90ee39b8087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), nullable=False))
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'firebase_uid',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
