"""initial tables

Revision ID: f90ee39b8087
Revises: None
Create Date: 2026-09-12 05:58:23.329602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f90ee39b8087'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_table('frequented_locations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fastest_arrival', sa.SmallInteger(), nullable=False),
    sa.Column('lowest_cost', sa.SmallInteger(), nullable=False),
    sa.Column('scenic_routes', sa.SmallInteger(), nullable=False),
    sa.Column('family_friendly', sa.SmallInteger(), nullable=False),
    sa.Column('avoid_tolls', sa.Boolean(), nullable=False),
    sa.Column('avoid_highways', sa.Boolean(), nullable=False),
    sa.Column('preferred_fuel_type', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('family_friendly BETWEEN 0 AND 10', name='ck_family_friendly_range'),
    sa.CheckConstraint('fastest_arrival BETWEEN 0 AND 10', name='ck_fastest_arrival_range'),
    sa.CheckConstraint('lowest_cost BETWEEN 0 AND 10', name='ck_lowest_cost_range'),
    sa.CheckConstraint('scenic_routes BETWEEN 0 AND 10', name='ck_scenic_routes_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'key', name='uq_user_pref_category_key')
    )
    op.create_table('vehicle_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=False),
    sa.Column('seat_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mirror_left', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mirror_right', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('steering_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('climate_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lighting_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_name', name='uq_vehicle_user_profile')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_settings')
    op.drop_table('user_preferences')
    op.drop_table('onboarding_profiles')
    op.drop_table('frequented_locations')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
